name: teardown
run-name: Destroy all entities in Seqera Platform from end-to-end with seqerakit
# This workflow can be triggered manually with GitHub actions workflow dispatch button.
# It will automate removing the e2e testing workspace.

on:
  workflow_dispatch:
jobs:
  e2e-testing:
    name:
    if: github.repository == 'seqeralabs/seqera-kit'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_GITHUB_PASSWORD: ${{ secrets.TOWER_GITHUB_PASSWORD }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AZURE_BATCH_KEY: ${{ secrets.AZURE_BATCH_KEY }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
      SENTIEON_LICENSE_BASE64: ${{ secrets.SENTIEON_LICENSE_BASE64 }}

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: 'uv.lock'

      - name: Install Tower CLI v0.9.1
        run: |
          wget https://github.com/seqeralabs/tower-cli/releases/download/v0.10.3/tw-linux-x86_64 \
          && chmod +x tw-linux-x86_64 \
          && sudo mv tw-linux-x86_64 /usr/local/bin/tw

      - name: teardown
        run: |
          mamba init
          temp_file=$(mktemp -q)
          echo $GOOGLE_KEY | base64 -d > $temp_file
          export GOOGLE_KEY=$temp_file

          uv run seqerakit --delete examples/yaml/seqerakit-e2e.yml
